version: '3.9'
name: weather-app
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - WEATHER_API_KEY=${WEATHER_API_KEY}
    ports:
      - ${APP_PORT}:${APP_PORT}
    networks:
      - mysqlnet
    depends_on:
      db:
        condition: service_healthy
        restart: true

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    hostname: db
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    ports:
      - 3306:3306
    networks:
      - mysqlnet
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

networks:
  mysqlnet: